using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AddressableAssets;

namespace Maze.Core.Localization
{
    /// <summary>
    /// Languages of the game (Addressable <see cref="Address"/>): code, own name, the system languages that choose it
    /// automatically and its <see cref="LocalizationTable"/> (loaded only when chosen). The first language is the
    /// base one: its texts fill gaps of the others and it is chosen when the system language is not supported.
    /// Generated by Maze → Dev → Build Localization.
    /// </summary>
    public sealed class LanguageCatalog : ScriptableObject
    {
        public const string Address = "Localization/Languages";

        [SerializeField] private List<LanguageEntry> _languages = new List<LanguageEntry>();

        public IReadOnlyList<LanguageEntry> Languages => _languages;

        /// <summary>Index of the language <paramref name="code"/>, or -1.</summary>
        public int IndexOf(string code)
        {
            if (string.IsNullOrEmpty(code)) return -1;
            for (var i = 0; i < _languages.Count; i++)
                if (_languages[i] != null && _languages[i].Code == code) return i;
            return -1;
        }

        /// <summary>
        /// The language to use: the saved one if it still exists, else the first language that lists
        /// <paramref name="system"/>, else the base language. -1 only for an empty catalog.
        /// </summary>
        public int Choose(string saved, SystemLanguage system)
        {
            var index = IndexOf(saved);
            if (index >= 0) return index;
            for (var i = 0; i < _languages.Count; i++)
                if (_languages[i] != null && _languages[i].Matches(system)) return i;
            return _languages.Count > 0 ? 0 : -1;
        }

        internal void SetLanguages(IEnumerable<LanguageEntry> languages)
        {
            _languages = new List<LanguageEntry>(languages);
        }
    }

    [Serializable]
    public sealed class LanguageEntry
    {
        [SerializeField] private string _code;
        [SerializeField] private string _nativeName;
        [SerializeField] private List<SystemLanguage> _systemLanguages = new List<SystemLanguage>();
        [SerializeField] private AssetReferenceT<LocalizationTable> _table = new AssetReferenceT<LocalizationTable>(string.Empty);

        public LanguageEntry(string code, string nativeName, IEnumerable<SystemLanguage> systemLanguages, string tableGuid)
        {
            _code = code;
            _nativeName = nativeName;
            _systemLanguages = new List<SystemLanguage>(systemLanguages);
            _table = new AssetReferenceT<LocalizationTable>(tableGuid ?? string.Empty);
        }

        /// <summary>"en", "ru", … (the column of the source table).</summary>
        public string Code => _code;

        /// <summary>The language's own name ("Русский").</summary>
        public string NativeName => _nativeName;

        public AssetReferenceT<LocalizationTable> Table => _table;

        public bool Matches(SystemLanguage system) => _systemLanguages.Contains(system);
    }
}
