using System;
using System.Collections.Generic;
using UnityEngine;

namespace Maze.Core.Localization
{
    /// <summary>
    /// Texts of one language: key → text (Addressable, only the chosen language is loaded). Generated by
    /// Maze → Dev → Build Localization from <see cref="LocalizationSource"/>; do not edit by hand. Keys not translated
    /// into this language hold the base-language text and are marked <see cref="IsMissing"/>.
    /// </summary>
    public sealed class LocalizationTable : ScriptableObject
    {
        [SerializeField] private string _language;
        [SerializeField] private string[] _keys = Array.Empty<string>();
        [SerializeField] private string[] _texts = Array.Empty<string>();
        [Tooltip("Keys whose text is the base language's (not translated yet).")]
        [SerializeField] private string[] _missing = Array.Empty<string>();

        [NonSerialized] private Dictionary<string, string> _lookup;
        [NonSerialized] private HashSet<string> _missingLookup;

        public string Language => _language;
        public int Count => _keys.Length;
        public IReadOnlyList<string> Keys => _keys;

        public bool TryGet(string key, out string text)
        {
            if (_lookup == null) BuildLookup();
            text = null;
            return key != null && _lookup.TryGetValue(key, out text);
        }

        /// <summary>The key is not translated into this language (its text is the base language's).</summary>
        public bool IsMissing(string key)
        {
            if (_lookup == null) BuildLookup();
            return key != null && _missingLookup.Contains(key);
        }

        internal void Fill(string language, IReadOnlyList<string> keys, IReadOnlyList<string> texts, IEnumerable<string> missing)
        {
            if (keys.Count != texts.Count) throw new ArgumentException("Keys and texts differ in count.");
            _language = language;
            _keys = new string[keys.Count];
            _texts = new string[texts.Count];
            for (var i = 0; i < keys.Count; i++)
            {
                _keys[i] = keys[i];
                _texts[i] = texts[i] ?? string.Empty;
            }

            _missing = new List<string>(missing ?? Array.Empty<string>()).ToArray();
            _lookup = null;
        }

        private void BuildLookup()
        {
            _lookup = new Dictionary<string, string>(_keys.Length, StringComparer.Ordinal);
            for (var i = 0; i < _keys.Length && i < _texts.Length; i++)
                if (_keys[i] != null) _lookup[_keys[i]] = _texts[i];
            _missingLookup = new HashSet<string>(_missing, StringComparer.Ordinal);
        }
    }
}
